wyeworks/elixir_console

lib/live_view_demo/sandbox.ex
lib/live_view_demo_web/live/console_live.ex

This PR aims to limit the resources consumed by user-generated commands in the console.
The strategy is to run the code in a task and then check the memory consumption periodically (every 50ms) until task finalization or timeout is reached. If memory usage in the process used to execute the command exceed a defined limit, the task is interrupted and the user is informed about this fact.
This solution should be complemented with other measures in order to execute code in a "sandboxed mode". In particular, we are likely to disallow code creating processes (eg `spawn`, `Task.async`, etc) because it's harder to control individual processes that could abuse memory usage or keep waiting for a message.

Limit memory usage and time execution

---

lib/elixir_console_web/live/console_live.ex
test/elixir_console_web/live/console_live_test.exs

- Write "Enum.coun" in the command input
- Press TAB key, so it is autocompleted to "Enum.count"
- Then delete the last letter, so it reads "Enum.coun" again.
- Press Tab key again
The input value is autocompleted to "Enum.count" again.
The input value is not changed.

Fix autocomplete issue when removing chars

---

assets/js/app.js
lib/elixir_console/autocomplete.ex
lib/elixir_console_web/live/console_live.ex
test/elixir_console_web/live/console_live_test.exs

Note that this specific issue is going to be tackled afterwards: https://app.clubhouse.io/wyeworks/story/74/autocomplete-from-the-middle-should-preserve-cursor-position

Autocomplete from caret position

---

assets/js/app.js
lib/elixir_console/autocomplete.ex
lib/elixir_console_web/live/console_live.ex
test/elixir_console/autocomplete_test.exs
test/elixir_console/sandbox/command_validator_test.exs
test/elixir_console/sandbox_test.exs
test/elixir_console_web/live/console_live_test.exs

This is a draft PR until #36 is reviewed and merged.
Here we complete the cursor position feature of our autocomplete. It adds the ability of change the cursor position to the most natural place, right after the last character of the autocompleted word.

Restore cursor position after autocomplete

---

lib/elixir_console/autocomplete.ex
lib/elixir_console/documentation.ex
test/elixir_console/autocomplete_test.exs

This PR adds the ability to autocomplete the module and function parts independently.
`Enu` will suggest `Emum`, `Enumerable`
`Lis` will autocomplete to `List`
When we have something like `Enum.co`, behavior does not change.. it will suggest `Enum.count` and `Enum.concat`

Autocomplete only module name

---

lib/elixir_console/contextual_help.ex
lib/elixir_console/documentation.ex
lib/elixir_console_web/live/console_live.ex
test/elixir_console/contextual_help_test.exs
test/elixir_console_web/live/console_live_test.exs

Completes the feature of displaying inline documentation for Elixir functions. Now, it also includes `Kernel` functions and macros.

Display docs for kernel functions

---

lib/elixir_console/autocomplete.ex
lib/elixir_console/documentation.ex
lib/elixir_console/sandbox/erlang_modules_absence.ex
test/elixir_console/autocomplete_test.exs
test/elixir_console/sandbox/command_validator_test.exs

Commands like `a = "foo #{33} bar"` were resulting in an error message.
Also, in this PR we add a missing module to the documentation caché module.

Fix string interpolation commands

---

lib/elixir_console/contextual_help.ex
test/elixir_console/contextual_help_test.exs

This commit fixes issues with the following expressions:
`[hd([45]) | 3]`
`[Enum.count([2,4])]`
`%{a: Enum.count([2,4])}`
`[a: Enum.count([2,4])]`

Fix problem with inline docs in nested expressions

---

lib/elixir_console/documentation.ex
lib/elixir_console/elixir_safe_parts.ex
test/elixir_console/autocomplete_test.exs

The idea is to prevent autocomplete Elixir modules or functions that are not allowed to be executed. Also, this changes prevent to display links to Elixir docs for code that is displayed in the console history but it was not safe enough to be run (so the user experience is consistent)

Do not autocomplete unsafe Elixir code

---

assets/js/app.js

In production environments we noticed that `suggest` and `position_caret` messages to the LV server are being sent in an unexpected order. This is an attempt to ensure that caret position message goes first and then the `suggest` message.

Fix autocomplete caret position issues attempt

---

lib/elixir_console/contextual_help.ex
test/elixir_console/contextual_help_test.exs
test/test_helper.exs

Two issues addressed. The cases that are fixed or alleviated are:
`~s(this is a string with "double" quotes, not 'single' ones)`
`Enum.find -50..50, &(rem(&1, 13) == 0)`
`File.stat!(foo).size`

More fixes

---

lib/elixir_console/application.ex
lib/elixir_console/documentation.ex
lib/elixir_console/sandbox.ex
lib/elixir_console_web/live/console_live.ex
lib/elixir_console_web/live/live_monitor.ex

This is an important PR since sandbox processes need to be terminated when connections are gone. Otherwise, we will be leaking resources.

Monitor sandbox processes and terminate them when user is gone

---

lib/elixir_console/sandbox.ex
lib/elixir_console/sandbox/erlang_modules_absence.ex
lib/elixir_console/sandbox/runtime_validations.ex
lib/elixir_console/sandbox/util.ex
test/elixir_console/sandbox/runtime_validations_test.exs
test/elixir_console/sandbox_test.exs

There are a certain number of cases where it is impossible to detect non-secure function invocations by only checking the code AST. For this reason, we are adding a way to modify the code AST before execution.
With this new approach, an internal function of the Sandbox is going to be executed prior to the user code invocation, resulting in a runtime error if the module or module/function to invocation is not included in our whitelists.

Add mechanism to validate functions invocations at runtime

---

lib/elixir_console/sandbox.ex
test/elixir_console/sandbox_test.exs

In previous commits the full environment was passed to `Code.eval_quoted`, but it made basic Erlang stuff accessible which is very bad.
We must try to keep the env passed to eval_quoted as simple as possible.
In fact, I'm now considering it could be a better approach to limit the dangerous part of Elixir (further work needed to validate it).

Fix important security issue due to env passed to eval_quoted

---

lib/elixir_console/sandbox/exclude_conversion_to_atoms.ex
test/elixir_console/sandbox/command_validator_test.exs

It was possible to dynamically create a significant number of atoms using the sigil_w with the atom modifier and combined with string interpolation.

Prevent atoms creation by using interpolation with the sigil_w

---

lib/elixir_console/sandbox/runtime_validations.ex
lib/elixir_console/sandbox/util.ex
test/elixir_console/sandbox/runtime_validations_test.exs
test/elixir_console/sandbox_test.exs

It fixes #76 by considering the particular case of the dot operator when used for function capturing.
Sections of the AST using function capturing is not modified after processing it to add the calls to `safe_invocation`.
Note we were forced to walk the AST tree in a "post-walk" manner, in addition to the original "pre-walk" callback we already had.

Fix issue with function capturing

---

assets/js/app.js
lib/elixir_console_web/templates/console/command_input.html.leex
lib/elixir_console_web/views/console/history_view.ex

Fixes #80 
In order to define event handlers in components we must set the `phx-target`, otherwise the event will try to be handled by the parent LiveView which after the latest refactor, it doesn't implement `handle_event/3` anymore.
Same happens when using `pushEvent` which will be handled by the LiveView. In this case, the fix is to use `pushEventTo` and pass a selector to something that is rendered by the LiveComponent so it gets handled properly.
All this changed slightly in latest versions of LiveView, making it a bit more straightforward, but for the current version this is the fix.

Set target component that will handle events

---

assets/js/app.js

The root of the issue was that two events were being sent for the same TAB key press, and depending on the order they're received the final state would be different.
It was seen only in staging because in fast local connections the second event always arrives last and that leaves the state in the expected shape.
To reproduce this locally I added `:timer.sleep(100)` in the handle_event functions for the `caret-position` and `suggest` events.

Fix caret wrongly being repositioned after TAB key

---

.github/dependabot.yml

Proposal is to start small, just doing this for mix deps and limit to 2 opened PRs for now.
We can tune later on based on experience.

Enable automatic update PRs for outdated mix deps

---

assets/js/app.js
lib/elixir_console_web/live/console_live/command_input_component.ex
test/elixir_console_web/live/console_live_test.exs

Now that we're able to get the caret position specifically as metadata on the suggest events we can stop syncing the caret position every time it changes on the client.
We still keep it synced on the client when it changes on the server.
This PR also fixes the problem where the caret was not being placed at the end after cycling through the history.

Stop syncing caret on the server

---

lib/elixir_console_web/live/console_live/command_input_component.ex
lib/elixir_console_web/live/console_live/command_input_component.html.leex

Motivation coming from the fact I was a bit confused by an event called "suggest" was being used to handle both the suggestions and the expression history.

Attempt to improve semantics of event name

---

.github/workflows/elixir.yml

Can help catch and make sure we fix warnings for tasks like #115.
Inspired by https://dashbit.co/blog/tests-with-warnings-as-errors.

Fail if mix.compile warnings in CI

---

lib/elixir_console/documentation.ex

When a function is called with a different arity than a existing one, we
should always show documentation to hint the user into the correct usage

Show links to documentation consistently

---

.github/workflows/elixir.yml
.tool-versions
elixir_buildpack.config
lib/elixir_console/contextual_help.ex
lib/elixir_console/elixir_safe_parts.ex
lib/elixir_console/sandbox.ex
mix.exs
test/elixir_console/autocomplete_test.exs

Upgrade elixir to v1.12

---

assets/js/app.js
lib/elixir_console_web/live/console_live/command_input_component.ex
lib/elixir_console_web/live/console_live/command_input_component.html.leex
test/elixir_console_web/live/console_live_test.exs

This is a refactor to separate the events sent when different keys are pressed.
I meant to also reduce the number of events sent by not sending a reset-input event everytime a different key in pressed but it required more work than expected so I'll leave it to a follow up PR

Handle all commandInput events in the hook

---

assets/js/app.js
lib/elixir_console_web/live/console_live/command_input_component.ex

This helps reducing considerably the events sent through the socket as
we don't need to send messages anymore when a different key is pressed.
This changes the current behavior slightly.
Previously if I was cycling through the history and pressed any key,
even keys like shift or cmd, it would reset the history and using up
arrow after that would start from the begining.
Now we continue from the same position we were.
I think this new behavior is not worse than what we had and it's definitely better when hitting keys that shouldn't affect the history, like non printable keys.
Overall we're sending events only when clear user actions are performed and no extra events to keep things in sync.

Only reset history counter when executing a command

---

lib/elixir_console_web/live/console_live/command_input_component.html.leex
test/elixir_console_web/live/console_live_test.exs

Now that we're on liveview 0.16 we can write tests for hooks that simulate the phx_target without having to define it in the template.

Remove unnecessary phx_target on hook

---

lib/elixir_console_web/live/console_live.html.heex

This works by using flex-direction: column-reverse so the browser will
treat the div as being reverted and will keep the scroll at the bottom
instead of top. The extra div is necessary so the content doesn't have
to be written inverted

Keep scroll at the bottom when new output is appended
